<?php
__('chirayomiFlag','books');
__('title','books');
__('author','books');
__('publisherName','books');
__('size','books');
__('isbn','books');
__('booksGenreId','books');


__('__availability_0','books');
__('__availability_1','books');
__('__availability_2','books');
__('__availability_3','books');
__('__availability_4','books');
__('__availability_5','books');
__('__availability_6','books');
__('availability_0','books');
__('availability_1','books');
__('availability_2','books');
__('availability_3','books');
__('availability_4','books');
__('availability_5','books');
__('availability_6','books');

__('outOfStockFlag_0','books');
__('outOfStockFlag_1','books');
__('chirayomiFlag_0','books');
__('chirayomiFlag_1','books');
__('limitedFlag_0','books');
__('limitedFlag_1','books');
__('__carrier_0','books');
__('__carrier_1','books');
__('carrier_0','books');
__('carrier_1','books');
__('__genreInformationFlag_0','books');
__('__genreInformationFlag_1','books');
__('genreInformationFlag_0','books');
__('genreInformationFlag_1','books');
__('size_0','books');
__('size_1','books');
__('size_2','books');
__('size_3','books');
__('size_4','books');
__('size_5','books');
__('size_6','books');
__('size_7','books');
__('size_8','books');
__('size_9','books');
__('size_10','books');

